import type { Product, Brand, Category } from "@/types/product"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Archer VR300",
    price: 1699,
    image: "/black-wireless-router-with-antennas.jpg",
    category: "Electronics",
    brand: "TP-Link",
    rating: 4.5,
    description: "High-performance wireless router with advanced features for seamless connectivity",
    quantity: 50,
    inStock: true,
    features: [
      "Dual-band Wi-Fi with speeds up to 1200 Mbps",
      "4 external antennas for extended coverage",
      "Advanced security protocols",
      "Easy setup and management",
    ],
  },
  {
    id: "2",
    name: "PIXMA G3420",
    price: 5999,
    image: "/black-canon-printer-with-ink-tanks.jpg",
    category: "Electronics",
    brand: "Canon",
    rating: 4.5,
    description: "All-in-one printer with continuous ink supply system for cost-effective printing",
    quantity: 30,
    inStock: true,
    features: [
      "Print, scan, and copy functionality",
      "Continuous ink supply system",
      "High-quality photo printing",
      "Wireless connectivity",
    ],
  },
  {
    id: "3",
    name: "EOS M50 Mark II Mirrorless Digital Camera With 15-45mm Lens Black",
    price: 19699,
    originalPrice: 19699,
    image: "/black-canon-mirrorless-camera-with-lens.jpg",
    category: "Electronics",
    brand: "Canon",
    rating: 4.3,
    description:
      "24.1 megapixel (aps-c) cmos sensor with iso 100-25600 (h: 51200) digic 8 image processor with auto lighting optimizer improved dual pixel cmos af and eye detection af (still/movie servo af support) 4k uhd 24p and hd 120p for slow motion variable-angle touchscreen lcd convenient for vlogging and various composition",
    quantity: 600,
    inStock: true,
    features: [
      "24.1 Megapixel APS-C CMOS sensor",
      "DIGIC 8 image processor",
      "4K UHD video recording",
      "Dual Pixel CMOS autofocus",
      "Variable-angle touchscreen LCD",
      "Built-in Wi-Fi and Bluetooth",
    ],
  },
  {
    id: "4",
    name: "PS5 DualSense",
    price: 1045,
    image: "/white-playstation-5-controller.jpg",
    category: "Electronics",
    brand: "Sony",
    rating: 4.8,
    description: "Wireless controller for PlayStation 5",
    quantity: 25,
    inStock: true,
  },
  {
    id: "5",
    name: "Galaxy Buds",
    price: 3999,
    image: "/black-wireless-earbuds-in-charging-case.jpg",
    category: "Electronics",
    brand: "Samsung",
    rating: 4.3,
    description: "True wireless earbuds with active noise cancellation",
    quantity: 40,
    inStock: true,
  },
  {
    id: "6",
    name: "WH-CH510 Wireless",
    price: 1949,
    image: "/black-over-ear-wireless-headphones.jpg",
    category: "Electronics",
    brand: "Sony",
    rating: 4.3,
    description: "Wireless on-ear headphones with long battery life",
    quantity: 35,
    inStock: true,
  },
  {
    id: "7",
    name: "Dell Gaming Laptop",
    price: 15999,
    image: "/black-gaming-laptop-with-colorful-keyboard.jpg",
    category: "Electronics",
    brand: "Dell",
    rating: 4.3,
    description: "High-performance gaming laptop with Intel Core processor",
    quantity: 10,
    inStock: true,
  },
  {
    id: "8",
    name: "ASUS Gaming Laptop",
    price: 18999,
    image: "/black-asus-gaming-laptop-with-rgb-keyboard.jpg",
    category: "Electronics",
    brand: "ASUS",
    rating: 4.3,
    description: "Premium gaming laptop with advanced cooling system",
    quantity: 8,
    inStock: true,
  },
  {
    id: "9",
    name: "ROG Gaming Laptop",
    price: 22999,
    image: "/black-rog-gaming-laptop-with-purple-accents.jpg",
    category: "Electronics",
    brand: "ASUS",
    rating: 4.8,
    description: "Top-tier gaming laptop with RTX graphics",
    quantity: 5,
    inStock: true,
  },
  {
    id: "10",
    name: "MacBook Pro",
    price: 25999,
    image: "/silver-macbook-pro-laptop.jpg",
    category: "Electronics",
    brand: "Apple",
    rating: 4.8,
    description: "Professional laptop with M2 chip",
    quantity: 12,
    inStock: true,
  },
  {
    id: "11",
    name: "Lenovo ThinkPad",
    price: 16999,
    image: "/black-lenovo-thinkpad-business-laptop.jpg",
    category: "Electronics",
    brand: "Lenovo",
    rating: 4.2,
    description: "Business laptop with enterprise security features",
    quantity: 20,
    inStock: true,
  },
  {
    id: "12",
    name: "Samsung 4K TV",
    price: 28999,
    image: "/large-samsung-4k-smart-tv-with-thin-bezels.jpg",
    category: "Electronics",
    brand: "Samsung",
    rating: 4.2,
    description: "55-inch 4K Smart TV with HDR support",
    quantity: 7,
    inStock: true,
  },
]

export const mockBrands: Brand[] = [
  {
    id: "1",
    name: "Canon",
    logo: "/canon-logo-black-text.jpg",
    description: "Leading manufacturer of cameras and printers",
    productCount: 45,
  },
  {
    id: "2",
    name: "Dell",
    logo: "/dell-logo-blue-text.jpg",
    description: "Computer technology company",
    productCount: 32,
  },
  {
    id: "3",
    name: "Lenovo",
    logo: "/placeholder.svg?height=100&width=200",
    description: "Multinational technology company",
    productCount: 28,
  },
  {
    id: "4",
    name: "Sony",
    logo: "/placeholder.svg?height=100&width=200",
    description: "Electronics and entertainment company",
    productCount: 38,
  },
  {
    id: "5",
    name: "Apple",
    logo: "/placeholder.svg?height=100&width=200",
    description: "Technology company known for innovative products",
    productCount: 25,
  },
  {
    id: "6",
    name: "Samsung",
    logo: "/placeholder.svg?height=100&width=200",
    description: "South Korean electronics company",
    productCount: 42,
  },
]

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Electronics",
    image: "/placeholder.svg?height=200&width=300",
    description: "Latest technology and electronic devices",
    productCount: 156,
  },
  {
    id: "2",
    name: "Fashion",
    image: "/placeholder.svg?height=200&width=300",
    description: "Trendy clothing and accessories",
    productCount: 89,
  },
  {
    id: "3",
    name: "Home & Garden",
    image: "/placeholder.svg?height=200&width=300",
    description: "Everything for your home and garden",
    productCount: 67,
  },
  {
    id: "4",
    name: "Sports",
    image: "/placeholder.svg?height=200&width=300",
    description: "Sports equipment and fitness gear",
    productCount: 43,
  },
]
